apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
  labels:
    app: wordpress
spec:
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
        - image: wordpress_img
          imagePullPolicy: Never
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_PASSWORD
              value: password
          ports:
            - containerPort: 5050
              name: wordpress
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/www/html
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-volume-claim